//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public string Bar_code { get; set; }
        public string ID_servicio { get; set; }
        public string Nombre { get; set; }
        public int Costo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Servicio Servicio { get; set; }
    }
}
