//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
/*
 * Esta clase contiene los atributos necesarios para el manejo de la informacion sobre esta entidad, ademas contiene relaciones entre tablas , las cuales 
 * seran utiles en los get generales donde muestra todas las conexiones de la entidad y ademas para no incumplir las restricciones creadas por las tablas
 * en sql server
 */
namespace Proyecto1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipos_planillas_empleados
    {
        public int Cedula { get; set; }
        public string ID_tipo_planilla { get; set; }
        public Nullable<int> Clases { get; set; }
        public Nullable<int> Horas { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Tipo_planilla Tipo_planilla { get; set; }
    }
}
