//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipos_planillas_empleados
    {
        public int Cedula { get; set; }
        public string ID_tipo_planilla { get; set; }
        public string Clases { get; set; }
        public string Horas { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Tipo_planilla Tipo_planilla { get; set; }
    }
}
