//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamiento
    {
        public string ID { get; set; }
        public string ID_servicio { get; set; }
        public string Nombre { get; set; }
    
        public virtual Servicio Servicio { get; set; }
    }
}
